image:
  # Adjust to the actual location of the image and version you want
  repository: nvcr.io/nim/meta/llama-3.1-70b-instruct
  tag: 1.1.2
imagePullSecrets:
  - name: registry-secret
model:
  name: meta/llama-3.1-70b-instruct
  ngcAPISecret: ngc-api
persistence:
  enabled: true
  storageClass: smb
#  existingClaim: "my-nim-nim-llm" # Remove it if you do not have an existing PVC share 
  accessMode: ReadWriteMany
  size: 200Gi 
  annotations:
    helm.sh/resource-policy: keep
statefulSet:
    enabled: true
resources:
  limits:
    nvidia.com/gpu: 4
startupProbe:
  failureThreshold: 1500