apiVersion: v1
kind: Pod
metadata:
  name: triton-perf
  namespace: nim
  labels:
    app: triton
spec:
  containers:
   - name: triton-perf
     image: nvcr.io/nvidia/tritonserver:24.08-py3-sdk
     command: ["sleep", "infinity"]
     resources:
       requests:
         ephemeral-storage: "10Gi"
       limits:
         ephemeral-storage: "20Gi"