apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.118.0.4  # Replace with your NFS server's IP
  share: /nfsshare
mountOptions:
  - vers=4.1
  - rsize=1048576
  - wsize=1048576
  - hard
  - tcp
  - noatime
  - nodiratime
  - timeo=600
  - retrans=2

