## Stack name: prometheus-community/kube-prometheus-stack
## Ref: https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-${version}/charts/kube-prometheus-stack
##


prometheusOperator:
  enabled: true

prometheus:
  enabled: true

  serviceMonitorSelectorNilUsesHelmValues: false

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
  
    additionalScrapeConfigs:
      - job_name: gpu-metrics
        scrape_interval: 1s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - gpu-operator
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: drop
            regex: .*-node-feature-discovery-master
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: kubernetes_node



grafana:
  enabled: true
  adminPassword: prom-operator # Please change the default password in production !!!
  persistence:
    enabled: true
    storageClassName: do-block-storage
    accessModes: ["ReadWriteOnce"]
    size: 20Gi

alertmanager:
  enabled: true


defaultRules:
  rules:
    etcd: false
    kubeScheduler: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false
